### 0. Declarations

In [1]:
import numpy as np

In [27]:
# We can create matrixes with using arange() to create array and using reshape() to shape array as matrix.

a = np.arange(1, 16).reshape((3, 5))

In [33]:
b = np.array([[4, 8, 9], [-5, 7, 3], [8, -4, 6], [6, 6, -5]])
b

array([[ 4,  8,  9],
       [-5,  7,  3],
       [ 8, -4,  6],
       [ 6,  6, -5]])

### 1. Advanced Matrix Operations
__1.1__ - Transposing Arrays

In [28]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [22]:
a.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

__1.1__ - Swapping Axes

In [21]:
a.swapaxes(0, 1)

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

__1.2__ - Inner Product of Two Matrixes

In [19]:
np.dot(a.T, a)

array([[158, 176, 194, 212, 230],
       [176, 197, 218, 239, 260],
       [194, 218, 242, 266, 290],
       [212, 239, 266, 293, 320],
       [230, 260, 290, 320, 350]])

### 2. Advanced Array Operations
__2.1__ - Taking Square Roots of Elements

In [24]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335]])

__2.2__ - Taking Exponential of Elements

In [26]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

__2.3__ - Sorting Arrays

In [37]:
np.sort(b)

array([[ 4,  8,  9],
       [-5,  3,  7],
       [-4,  6,  8],
       [-5,  6,  6]])

In [39]:
np.sort(b, axis = 0)

array([[-5, -4, -5],
       [ 4,  6,  3],
       [ 6,  7,  6],
       [ 8,  8,  9]])

In [36]:
np.sort(b, axis = 1)

array([[ 4,  8,  9],
       [-5,  3,  7],
       [-4,  6,  8],
       [-5,  6,  6]])