### 0. Declarations

In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

In [14]:
b = np.array([[8, 7, 8, 7], [7, 8, 7, 8]])

In [15]:
c = np.array([[5, 6, 5, 6], [6, 5, 6, 5]])

In [16]:
d = np.array([[1, 2], [3, 4]])

In [17]:
e = np.array([[-1, -2], [-3, -4]])

### 1. Reshaping Arrays
We can reshape arrays as long as the new shape's bound is equal.

In [5]:
a.reshape(4, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [6]:
a.reshape(2, 8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [7]:
a.reshape(8, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [8]:
a.reshape(2, 4, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [9]:
a.reshape(2, 2, 2, 2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

### 2. Stacking Arrays
We can stack arrays horizontally and vertically asl long as H and V sizes are equal.<br>
*np.vstack( )* > vertical stacking<br>
*np.hstack( )* > horizontal stacking

In [19]:
np.vstack((b, c))

array([[8, 7, 8, 7],
       [7, 8, 7, 8],
       [5, 6, 5, 6],
       [6, 5, 6, 5]])

In [20]:
np.hstack((d, e))

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

In [21]:
np.vstack((b, c, b))

array([[8, 7, 8, 7],
       [7, 8, 7, 8],
       [5, 6, 5, 6],
       [6, 5, 6, 5],
       [8, 7, 8, 7],
       [7, 8, 7, 8]])