### 0. Declarations

In [6]:
import numpy as np

### 1. Initializing Different Types of Arrays
__1.1__ - We can initialize "*all 0s matrix*" as *np.zeros((n_of_row, n_of_column))*.

In [7]:
a = np.zeros((2, 3), dtype = "int32")
a

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

__1.2__ - We can initialize "*all 1s matrix*" as *np.ones((n_of_row, n_of_column))*.

In [8]:
b = np.ones((3, 2), dtype = "int32")
b

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

__1.3__ - We can create a *matrix filled with one given number* as *np.full((n_of_row, n_of_column), number)*.

In [9]:
c = np.full((3, 3), -3)
c

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

### 2. Initializing Arrays From Random Numbers
__2.1__ - We can initialize *random decimal number filled matrix* as *np.random.rand(n_of_row, n_of_column)*.

In [10]:
d = np.random.rand(2, 2)
d

array([[0.22861772, 0.8015232 ],
       [0.27379084, 0.60175374]])

__2.2__ - We can initialize *random integer number filled matrix* as *np.random.randint(lower_bound, upper_bound, (n_of_row, n_of_column))*.

In [11]:
e = np.random.randint(1, 9, (2, 2))
e

array([[2, 5],
       [3, 5]])

### 3. Initializing Identity Matrixes
__3.1__ - We can initialize an *identity matrix* as *np.identity(size)*.

In [12]:
f = np.identity(5, dtype = "int32")
f

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

### 4. Copying Arrays
When copying arrays, we should use *.copy()*<br>
If we use assignment, new reference will point the same array.

In [15]:
b = a.copy()
b

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)