### 0. Declarations

In [4]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
b = np.array([1, 0, 1, 0])

### 1. Basic Mathematics
We can do addition, substraction, multiplication and division to whole array, as *array_name (operand) number*.

In [7]:
a + 3

array([4, 5, 6, 7])

In [8]:
a - 5

array([-4, -3, -2, -1])

In [9]:
a * 3

array([ 3,  6,  9, 12])

In [10]:
a / 4

array([0.25, 0.5 , 0.75, 1.  ])

We can do same operations with an array instead of a number.

In [11]:
a + b

array([2, 2, 4, 4])

In [12]:
a - b

array([0, 2, 2, 4])

In [13]:
a * b

array([1, 0, 3, 0])

### 2. Taking Power and Trigonometry
We can take the elements power with a number, or do some trigonometry operations on them.

In [ ]:
a ** 3

In [ ]:
np.cos(a)

### 3. Linear Algebra
We can do linear algebra operations on arrays such as finding determinant, matrix multiplication etc.

In [16]:
x = np.ones((2, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
y = np.full((3, 2), 2)
y

array([[2, 2],
       [2, 2],
       [2, 2]])

In [23]:
z = np.matmul(x, y)
z

array([[6., 6.],
       [6., 6.]])

In [26]:
np.linalg.det(z)

0.0