### 0. Declarations

In [1]:
import numpy as np

In [37]:
a = np.array([[1,2,3],[4,5,6]])

In [60]:
b = np.array([2, 4, 6, 8, -1])

In [66]:
wt = np.array([0.25, 0.50, 0.25, 0.50, 0.75])

In [71]:
c = np.array([1, 2, 3, 4, 5])

### 1. Basic Statistics
We can do basic statistics on arrays such as taking minimum, maximum or sum.

In [8]:
np.min(a)

1

In [4]:
a.max()

6

In [23]:
np.sum(a)

21

We can add an axis info to the operation.

In [25]:
np.min(a, axis = 0)

array([1, 2, 3])

In [26]:
np.max(a, axis = 1)

array([3, 6])

In [5]:
np.sum(a, axis = 0)

array([5, 7, 9])

In [6]:
np.sum(a, axis = 1)

array([ 6, 15])

### 2. Statistical Operations
*np.mean(array_name)* > gives us the mean of an array or a specified axis.

In [27]:
np.mean(a)

3.5

In [22]:
np.mean(a, axis = 1)

array([2., 5.])

*np.median(array_name)* > gives us the median value of an array or a specified axis.

In [28]:
np.median(a)

3.5

In [29]:
np.median(a[1])

5.0

In [30]:
np.median(a[:, 0])

2.5

In [31]:
np.median(a, axis = 1)

array([2., 5.])

*np.var(array_name)* > gives us the variance value of an array or a specified axis.

In [32]:
np.var(a)

2.9166666666666665

In [33]:
np.var(a, axis = 1)

array([0.66666667, 0.66666667])

*np.std(array_name)* > gives us the standart deviation of an array or a specified axis.

In [34]:
np.std(a)

1.707825127659933

In [35]:
np.std(a, axis = 0)

array([1.5, 1.5, 1.5])

In [36]:
np.std(a, axis = 1)

array([0.81649658, 0.81649658])

*np.average(array_name, weights)* > gives us the weighted average of an array.

In [62]:
np.average(b, weights = wt)

3.2222222222222223

*np.percentile(array_name, percentile)* > gives us a value of an array at the given percentile.

In [75]:
np.percentile(c, 50)

3.0