### 0. Declarations

In [9]:
import numpy as np

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [13]:
a.ndim

2

In [12]:
a.shape

(3, 3)

In [17]:
b = np.array([[[3, 6, 9], [1, 2, 3]], [[2, 4, 6], [1, 2, 3]]])

In [18]:
b.ndim

3

In [19]:
b.shape

(2, 2, 3)

### 1. Accessing Elements
We can get a spesific element as *[row, column]*.<br>
If its dimension is higher than 2, we can get as *[dim1, dim2, dim3, ...]*.

In [14]:
a[1, 2]

6

In [34]:
b[1, 0, 2]

6

### 2. Accessing Rows and Columns
We can get a spesific row as *[row, :]*.<br>
We can get a spesific column as *[:, column]*.<br>
"*:*" stands for all items in the array.

In [15]:
a[2, :]

array([7, 8, 9])

In [16]:
a[:, 2]

array([3, 6, 9])

We can get a range of a row or column as "*start_index:end_index*" (end index is not included).

In [37]:
a[1, 0:2]

array([4, 5])

### 3. Updating Elements, Rows and Columns
We can update an element using assignment operator "*=*".

In [40]:
a[1, 2] = -1
a

array([[ 1,  2,  3],
       [ 4,  5, -1],
       [ 7,  8,  9]])

In [43]:
a[1] = [-1, -1, -1]
a

array([[ 1,  2,  3],
       [-1, -1, -1],
       [ 7,  8,  9]])

In [51]:
b[1, :, 1] = [-1, -1]
b

array([[[ 3,  6,  9],
        [ 1,  2,  3]],

       [[ 2, -1,  6],
        [ 1, -1,  3]]])