### 0. Declarations

In [1]:
import numpy as np

### 1. Load Data From File
We can get data from an external file.

In [6]:
a = np.genfromtxt("data.txt", delimiter = ",", dtype = "int16")
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int16)

### 2. Advanced Indexing and Boolean Masking
We can pass some conditions while listing data.

In [7]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11, 12], dtype=int16)

We can give some indexes as list.

In [15]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b[[1, 3, 5, -1]]

array([2, 4, 6, 9])

We can boolean mask the data with a condition.

In [30]:
(a > 5)

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
(a > 5) & (a < 10)

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True, False, False, False]])

In [24]:
np.any(a > 5, axis = 1)

array([False,  True,  True])