### 1. Importing Numpy

In [1]:
import numpy as np

### 2. Creating Arrays
We can create 1, 2, 3 or more dimensioned arrays with this.

In [11]:
a = np.array([1, 3, 5, 7, 9])
a

array([1, 3, 5, 7, 9])

In [12]:
b = np.array([[1, 3, 5, 7, 9], [0, 2, 4, 6, 8]])
b

array([[1, 3, 5, 7, 9],
       [0, 2, 4, 6, 8]])

In [27]:
c = np.array([[[3, 6, 9], [1, 2, 3]], [[2, 4, 6], [1, 2, 3]]])
c

array([[[3, 6, 9],
        [1, 2, 3]],

       [[2, 4, 6],
        [1, 2, 3]]])

In [29]:
d = np.array([3.5, 7.0, 10.5])
d

array([ 3.5,  7. , 10.5])

### 3. Getting Dimension
This gives us the dimension of the array.

In [13]:
a.ndim

1

In [14]:
b.ndim

2

In [20]:
c.ndim

3

### 4. Getting Shape
This gives us the shape of the array.

In [15]:
a.shape

(5,)

In [22]:
b.shape

(2, 5)

In [26]:
c.shape

(2, 2, 3)

### 5. Getting Type
This gives us the element type of the array.

In [17]:
a.dtype

dtype('int64')

In [18]:
b.dtype

dtype('int64')

In [30]:
d.dtype

dtype('float64')

### 6. Getting Size
*.itemsize* > gives us the size of the items in the array.<br>
*.nbytes* > gives us the size of the whole array.

In [43]:
a.itemsize

8

In [44]:
a.nbytes

40

In [45]:
# Creating array with special size.

e = np.array([3, 6, 9], dtype = "int16")

In [46]:
e.itemsize

2

In [47]:
e.nbytes

6