### 0. Declarations

In [36]:
import numpy as np

In [37]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

In [38]:
b = np.array([[8, 7, 8, 7], [7, 8, 7, 8]])

In [39]:
c = np.array([[5, 6, 5, 6], [6, 5, 6, 5]])

In [40]:
d = np.array([[1, 2], [3, 4]])

In [41]:
e = np.array([[-1, -2], [-3, -4]])

### 1. Reshaping Arrays
*.reshape( )* > We can reshape arrays as long as the new shape's bound is equal.<br>
*.ravel( )* > We can flatten arrays to one dimension.

In [42]:
a.reshape(4, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
a.reshape(2, 8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [44]:
a.reshape(8, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [45]:
a.reshape(2, 4, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [46]:
a.reshape(2, 2, 2, 2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [47]:
x = a.reshape(4, 4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 2. Stacking Arrays
We can stack arrays horizontally and vertically asl long as H and V sizes are equal.<br>
*np.vstack( )* > vertical stacking<br>
*np.hstack( )* > horizontal stacking

In [48]:
np.vstack((b, c))

array([[8, 7, 8, 7],
       [7, 8, 7, 8],
       [5, 6, 5, 6],
       [6, 5, 6, 5]])

In [49]:
np.hstack((d, e))

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

In [50]:
np.vstack((b, c, b))

array([[8, 7, 8, 7],
       [7, 8, 7, 8],
       [5, 6, 5, 6],
       [6, 5, 6, 5],
       [8, 7, 8, 7],
       [7, 8, 7, 8]])

### 2. Concatenating Arrays
We can concatenate arrays horizontally and vertically with *np.concatenate([array1_name, array2_name], axis = n)*.

In [51]:
np.concatenate([b, c], axis = 0)

array([[8, 7, 8, 7],
       [7, 8, 7, 8],
       [5, 6, 5, 6],
       [6, 5, 6, 5]])

In [52]:
np.concatenate([b, c], axis = 1)

array([[8, 7, 8, 7, 5, 6, 5, 6],
       [7, 8, 7, 8, 6, 5, 6, 5]])